title: Chip CAD Guide
description: Concise Glade + SpiceOpus tutorials for the CNM25 CMOS APDK.
remote_theme: just-the-docs/just-the-docs
plugins:
  - jekyll-remote-theme
search_enabled: true
color_scheme: dark
enable_dark_mode: true
logo: "media/SFU_logo.png"

defaults:
  - scope:
      path: ""
    values:
      layout: default